### ISSUE TITLE
[EPIC] Apache pulsar

### ISSUE THREAD

**Issue by ClementToni** [celte-team/celte-system#76]
The goal of this EPIC is to remove kafka from our stack due to performance issue and to use [Apach Pulsar](https://pulsar.apache.org/docs/4.0.x/) instead. This requires a refacto of the code:
- [x] SDK
- [x] Library
- [x] Master
- [x] #83
- [x] RPC #82 
- [x] Input
- [x] #84
- [x] #85
- [x] #75 
- [x] #79

**Comment by TheoPAWELEC** [comment]
Force à vous
